/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dao;

import dao.model.Wybieg;
import dao.mappers.IMapResultSetIntoEntity;
import dao.model.IHaveId;
import dao.model.Zwierze;
import dao.repositories.IRepositoryWybieg;
import dao.uow.IUnitOfWork;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author TKK
 */
public class WybiegRepository extends RepositoryBase<Wybieg> implements IRepositoryWybieg {

    public static final String TABLE_NAME = "wybiegi";

    public WybiegRepository(Connection connection, IMapResultSetIntoEntity<Wybieg> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    @Override
    protected String insertSql() {
        return "insert into "
                + tableName()
                + "(id_typ_wybiegu, stan_wybiegu) values"
                + "(?,?)";
    }

    @Override
    protected String updateSql() {
        return "update "
                + tableName()
                + " set (id_typ_wybiegu, stan_wybiegu) ="
                + "(?,?)"
                + " where "
                + "id = ?";
    }

    @Override
    protected void setUpdate(Wybieg entity) throws SQLException {
        update.setInt(1, entity.getRodzajWybiegu());
        update.setString(2, entity.getStanWybiegu().toString());
        update.setInt(3, entity.getId());
    }

    @Override
    protected void setInsert(Wybieg entity) throws SQLException {
        insert.setInt(1, entity.getRodzajWybiegu());
        insert.setString(2, entity.getStanWybiegu().toString());
    }

    @Override
    protected String createTableSql() {
        return "create table "
                + tableName()
                + " (id int generated by default as identity primary key,"
                + "id_typ_wybiegu int,"
                + "stan_wybiegu varchar(15))";
    }

    @Override
    protected String tableName() {
        return TABLE_NAME;
    }

    @Override
    public List<Wybieg> pobierzListeWybiegow(Zwierze zwierze) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected void insertNecessaryData() throws SQLException {
    }

}
